export const textVariants = {
    original: 
        "The weather today is quite unpredictable and seems to change every few minutes. Looking out the window, I can see clouds gathering in the distance.\nIt might rain heavily, or it might turn into a beautiful sunny afternoon. The meteorologists have been giving conflicting forecasts all week.\nI'm not really sure what to expect from Mother Nature today. The humidity feels high, and there's a strange stillness in the air.\nMaybe I should just stay inside today and work on some indoor projects. It would be safer than getting caught in a sudden downpour.",
    professional: 
        "Current meteorological conditions show significant variability with rapid atmospheric changes. Observational data indicates cumulus cloud formation.\nPrecipitation probability is elevated, though periods of solar radiation are also feasible. Forecasting models have shown inconsistent results.\nEnvironmental assessment suggests considerable uncertainty in atmospheric behavior. Relative humidity is high with minimal air circulation.\nOptimal risk management protocols recommend indoor activities to mitigate exposure to potential precipitation events.",
    casual: 
        "Honestly, the weather's all over the place today! 🌦️ One minute it looks like it's gonna pour, the next minute the sun's trying to peek through.\nCould be rainy, could be sunny - your guess is as good as mine at this point! 🤷‍♀️ The weather app keeps changing its prediction every hour.\nI have zero clue what's happening up there in the sky today. It feels muggy and weird, like when you know something's about to go down.\nThink I'll just Netflix and chill instead of dealing with whatever chaos is brewing outside. 😎 Better to be cozy indoors than getting soaked.",
    creative: 
        "Nature is painting an uncertain canvas today, with silver clouds dancing across cerulean hope. 🎨 The sky seems to be having an identity crisis.\nThe heavens whisper secrets of rain and sun in the same breath, like a poet torn between melancholy and joy. Each cloud carries stories of distant places.\nWeather gods are playing cosmic dice above, rolling thunder and lightning in one hand while juggling rays of golden warmth in the other.\nPerhaps home is today's greatest adventure, wrapped in familiar walls while the world performs its theatrical weather show. ✨"
};
